CREATE EXTERNAL TABLE `bkpf_analytics`(
  `bukrs` string,
  `belnr` string,
  `gjahr` string,
  `blart` string,
  `bldat` date,
  `budat` date,
  `monat` string,
  `cpudt` date,
  `cputm` timestamp,
  `aedat` date,
  `upddt` date,
  `wwert` date,
  `usnam` string,
  `tcode` string,
  `bvorg` string,
  `xblnr` string,
  `dbblg` string,
  `stblg` string,
  `stjah` string,
  `bktxt` string,
  `waers` string,
  `kursf` double,
  `kzwrs` string,
  `kzkrs` double,
  `bstat` string,
  `xnetb` string,
  `frath` double,
  `xrueb` string,
  `glvor` string,
  `grpid` string,
  `dokid` string,
  `arcid` string,
  `iblar` string,
  `awtyp` string,
  `awkey` string,
  `fikrs` string,
  `hwaer` string,
  `hwae2` string,
  `hwae3` string,
  `kurs2` double,
  `kurs3` double,
  `basw2` string,
  `basw3` string,
  `umrd2` string,
  `umrd3` string,
  `xstov` string,
  `stodt` date,
  `xmwst` string,
  `curt2` string,
  `curt3` string,
  `kuty2` string,
  `kuty3` string,
  `xsnet` string,
  `ausbk` string,
  `xusvr` string,
  `duefl` string,
  `awsys` string,
  `txkrs` double,
  `ctxkrs` double,
  `lotkz` string,
  `xwvof` string,
  `stgrd` string,
  `ppnam` string,
  `brnch` string,
  `numpg` string,
  `adisc` string,
  `xref1_hd` string,
  `xref2_hd` string,
  `xreversal` string,
  `reindat` date,
  `rldnr` string,
  `ldgrp` string,
  `propmano` string,
  `xblnr_alt` string,
  `vatdate` date,
  `doccat` string,
  `xsplit` string,
  `cash_alloc` string,
  `follow_on` string,
  `xreorg` string,
  `subset` string,
  `kurst` string,
  `kursx` double,
  `kur2x` double,
  `kur3x` double,
  `xmca` string,
  `resubmission` date,
  `sapf15_status` string,
  `psoty` string,
  `psoak` string,
  `psoks` string,
  `psosg` string,
  `psofn` string,
  `intform` string,
  `intdate` date,
  `psobt` date,
  `psozl` string,
  `psodt` date,
  `psotm` timestamp,
  `fm_umart` string,
  `ccins` string,
  `ccnum` string,
  `ssblk` string,
  `batch` string,
  `sname` string,
  `sampled` string,
  `exclude_flag` string,
  `blind` string,
  `offset_status` string,
  `offset_refer_dat` date,
  `penrc` string,
  `knumv` string)
PARTITIONED BY (
  `year` string,
  `month` string,
  `day` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://analytics-koandina-dev/regional/sap/bkpf'
TBLPROPERTIES (
  'compressionType'='SNAPPY',
  'projection.enabled'='false',
  'skip.header.line.count'='0',
  'spark.sql.create.version'='2.2 or prior',
  'spark.sql.sources.schema.numPartCols'='3',
  'spark.sql.sources.schema.numParts'='2',
  'spark.sql.sources.schema.partCol.0'='year',
  'spark.sql.sources.schema.partCol.1'='month',
  'spark.sql.sources.schema.partCol.2'='day',
  'transient_lastDdlTime'='1653437695')