CREATE EXTERNAL TABLE db_koandina_cl_stage.hrpa9852_stagesec(
PERNR string,
SUBTY string,
OBJPS string,
SPRPS string,
ENDDA string,
BEGDA string,
SEQNR string,
AEDTM string,
UNAME string,
HISTO string,
ITXEX string,
REFEX string,
ORDEX string,
ITBLD string,
PREAS string,
FLAG1 string,
FLAG2 string,
FLAG3 string,
FLAG4 string,
RESE1 string,
RESE2 string,
GRPVL string,
TIPVEND string,
TIP_VEN string,
WAERS string,
LGART01 string,
ANZHL01 string,
BETRG01 string,
LGART02 string,
ANZHL02 string,
BETRG02 string,
LGART03 string,
ANZHL03 string,
BETRG03 string,
LGART04 string,
ANZHL04 string,
BETRG04 string,
LGART05 string,
ANZHL05 string,
BETRG05 string,
LGART06 string,
BETRG06 string,
ANZHL06 string,
LGART07 string,
ANZHL07 string,
BETRG07 string,
LGART08 string,
ANZHL08 string,
BETRG08 string,
LGART09 string,
ANZHL09 string,
BETRG09 string,
LGART10 string,
ANZHL10 string,
BETRG10 string,
LGART11 string,
ANZHL11 string,
BETRG11 string,
LGART12 string,
ANZHL12 string,
BETRG12 string,
LGART13 string,
ANZHL13 string,
BETRG13 string,
LGART14 string,
ANZHL14 string,
BETRG14 string,
LGART15 string,
ANZHL15 string,
BETRG15 string,
LGART16 string,
ANZHL16 string,
BETRG16 string,
LGART17 string,
ANZHL17 string,
BETRG17 string,
LGART18 string,
ANZHL18 string,
BETRG18 string,
LGART19 string,
ANZHL19 string,
BETRG19 string,
LGART20 string,
ANZHL20 string,
BETRG20 string,
COD_UEN string,
COD_CVEND string,
COD_ZON string,
COD_RUTA string,
COD_CVAR string,
MIN_TABLA string,
TARGET string,
ZBONOGD string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://stagesec-koandina-dev/cl/sap/hrpa9852'
TBLPROPERTIES (
'compressionType'='SNAPPY',
'skip.header.line.count'='1')