CREATE EXTERNAL TABLE db_koandina_regional_stage.hrpa0743_stagesec(
PERNR string,
SUBTY string,
OBJPS string,
SPRPS string,
ENDDA string,
BEGDA string,
SEQNR string,
AEDTM string,
UNAME string,
HISTO string,
ITXEX string,
REFEX string,
ORDEX string,
ITBLD string,
PREAS string,
FLAG1 string,
FLAG2 string,
FLAG3 string,
FLAG4 string,
RESE1 string,
RESE2 string,
GRPVL string,
INTY1 string,
INBD1 string,
INED1 string,
INRE1 string,
INAT1 string,
INTY2 string,
INBD2 string,
INED2 string,
INRE2 string,
INAT2 string,
INTY3 string,
INBD3 string,
INED3 string,
INRE3 string,
INAT3 string,
INTY4 string,
INBD4 string,
INED4 string,
INRE4 string,
INAT4 string,
INTY5 string,
INBD5 string,
INED5 string,
INRE5 string,
INAT5 string,
OFFDT string,
DIACD string,
INVDT string,
DAKCR string,
OFFC1 string,
OFFC2 string,
OFFC3 string,
OFFC4 string,
OFFC5 string,
HEABD string,
HEAED string,
INVPR string,
COIP1 string,
COIN1 string,
COIP2 string,
COIN2 string,
COIP3 string,
COIN3 string,
TYPER string,
REPPR string,
REPNA string,
MINPR string,
DACKP string,
OUCD1 string,
OUDE1 string,
OUDF1 string,
OUDR1 string,
OUMT1 string,
OUAT1 string,
OUPR1 string,
OUIN1 string,
OUND1 string,
OUCD2 string,
OUDE2 string,
OUDF2 string,
OUDR2 string,
OUMT2 string,
OUAT2 string,
OUPR2 string,
OUIN2 string,
OUND2 string,
OUCD3 string,
OUDE3 string,
OUDF3 string,
OUDR3 string,
OUMT3 string,
OUAT3 string,
OUPR3 string,
OUIN3 string,
OUND3 string,
WAERS string,
COIM1 string,
COIM2 string
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://stagesec-koandina-dev/regional/sap/hrpa0743'
TBLPROPERTIES (
'compressionType'='SNAPPY',
'skip.header.line.count'='1')