CREATE EXTERNAL TABLE db_koandina_cl_analyticssec.z6hrmmo1_analyticssec
(
PABRP string,
PABRJ string,
BUKRS string,
PERNR string,
NACHN string,
NACH2 string,
VORNA string,
ANTIG string,
NATIO string,
FATXT string,
SINDI string,
PBTXT string,
BTRTX string,
RUT string,
UNAME string,
FING string,
FBAJA string,
FNAC string,
SEXO string,
PLANS string,
PLANSTXT string,
STELL string,
TRFAR string,
TARTX string,
TCTTO string,
FFIN string,
KOSTL string,
KTEXT string,
GERE1 string,
GERE2 string,
ROTAC string,
ROL string,
FTE string,
COMUNA string,
SUELDOBASE string,
AFP string,
NOMAFP string,
PERSK string,
PERSKTXT string,
TURNOCOD string,
TURNODESCRIP string,
NOMISAPRE string,
ORGEH string,
ORGEH_TXT string,
GRADO_HAY string,
INC_LABORAL string
)
ROW FORMAT SERDE
'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS PARQUET
LOCATION 's3://analyticssec-koandina-$ENV/cl/sap/z6hrmmo1/'
TBLPROPERTIES ('compressionType'='SNAPPY');