CREATE OR REPLACE VIEW db_koandina_regional_analyticssec.vw_reg_hrpad25_analyticssec AS
select
    hrpad25.adatanr,
    hrpad25.tpartdocno,
    hrpad25.manzl,
    hrpad25.budat,
    hrpad25.intex,
    hrpad25.kkost,
    hrpad25.kwaer,
    hrpad25.kokrs,
    hrpad25.kostl,
    hrpad25.zdata,
    hrpad25.belnr,
    hrpad25.confirmed,
    hrpad25.passed,
    hrpad25.failed,
    hrpad25.follow_up,
    hrpad25.caatr,
    hrpad25.prevsclas,
    hrpad25.prevsobid,
    hrpad25.event,
    hrpad25.status,
    hrpad25.refdocno,
    hrpad25.refdocitem,
    hrpad25.documentdate,
    hrpad25.postingdate,
    hrpad25.docuname,
    hrpad25.creditbelnr,
    hrpad25.creditstatus,
    hrpad25.scostcenter,
    hrpad25.receiveorder,
    hrpad25.rsalesorder,
    hrpad25.rsalesitem,
    hrpad25.activitytype,
    hrpad25.quantity,
    hrpad25.unit,
    hrpad25.sold_to,
    hrpad25.bill_to,
    hrpad25.payer,
    hrpad25.ship_to,
    hrpad25.net_price,
    hrpad25.tax_price,
    hrpad25.purch_order,
    hrpad25.cc_type,
    hrpad25.cc_number,
    hrpad25.cc_valid_to,
    hrpad25.cc_name,
    hrpad25.rwbselement,
    hrpad25.pay_status,
    hrpad25.cc_number_check,
    hrpad25.cc_auth_status,
    hrpad25.refdocseqnr,
    hrpad25.learn_status,
    hrpad25.access_counter
from db_koandina_regional_analyticssec.hrpad25_analyticssec hrpad25



