CREATE EXTERNAL TABLE db_koandina_regional_raw.hrpa0021_rawsec(
PERNR STRING,
SUBTY STRING,
OBJPS STRING,
SPRPS STRING,
ENDDA STRING,
BEGDA STRING,
SEQNR STRING,
AEDTM STRING,
UNAME STRING,
HISTO STRING,
ITXEX STRING,
REFEX STRING,
ORDEX STRING,
ITBLD STRING,
PREAS STRING,
FLAG1 STRING,
FLAG2 STRING,
FLAG3 STRING,
FLAG4 STRING,
RESE1 STRING,
RESE2 STRING,
GRPVL STRING,
FAMSA STRING,
FGBDT STRING,
FGBLD STRING,
FANAT STRING,
FASEX STRING,
FAVOR STRING,
FANAM STRING,
FGBOT STRING,
FGDEP STRING,
ERBNR STRING,
FGBNA STRING,
FNAC2 STRING,
FCNAM STRING,
FKNZN STRING,
FINIT STRING,
FVRSW STRING,
FVRS2 STRING,
FNMZU STRING,
AHVNR STRING,
KDSVH STRING,
KDBSL STRING,
KDUTB STRING,
KDGBR STRING,
KDART STRING,
KDZUG STRING,
KDZUL STRING,
KDVBE STRING,
ERMNR STRING,
AUSVL STRING,
AUSVG STRING,
FASDT STRING,
FASAR STRING,
FASIN STRING,
EGAGA STRING,
FANA2 STRING,
FANA3 STRING,
BETRG STRING,
TITEL STRING,
EMRGN STRING,
ZNUMEROCONTACTO STRING,
ZPARENTESCO STRING
)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'quoteChar'='\"', 
  'separatorChar'='\;') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://rawsec-koandina-prod/regional/sap/hrpa0021'
TBLPROPERTIES (
  'skip.header.line.count'='1', 
  'spark.sql.partitionProvider'='catalog')